# example netlify.toml
[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

## Uncomment to use this redirect for Single Page Applications
## Not needed for static site generators.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
    NODE_VERSION = "14.15.0"
    NPM_VERSION = "8.5.5"